In [1]:
import pandas as pd
df = pd.read_csv("weather.csv")

In [4]:
df

,time,air_temperature,wind_from_direction,wind_speed,wind_speed_of_gust,relative_humidity,air_pressure_at_mean_sea_level,visibility_in_air,thunderstorm_probability,probability_of_frozen_precipitation,...,cloud_top_altitude,precipitation_amount_mean_deterministic,precipitation_amount_mean,precipitation_amount_min,precipitation_amount_max,precipitation_amount_median,probability_of_precipitation,precipitation_frozen_part,predominant_precipitation_type_at_surface,symbol_code
0,2026-08-02T22:00:00Z,15.9,228,2.7,6.6,55,1016.0,34.7,1,0.0,...,9999,0.0,0.0,0.0,0.0,0.0,0,-9,0,1
1,2026-08-02T23:00:00Z,15.2,228,3.1,6.2,58,1016.3,32.7,1,0.0,...,9999,0.0,0.0,0.0,0.0,0.0,0,-9,0,1
2,2026-08-03T00:00:00Z,14.9,234,3.6,7.2,60,1016.5,31.3,1,0.0,...,9999,0.0,0.0,0.0,0.0,0.0,0,-9,0,1
3,2026-08-03T01:00:00Z,14.4,234,3.5,7.4,63,1016.6,29.2,1,0.0,...,9999,0.0,0.0,0.0,0.0,0.0,0,-9,0,1
4,2026-08-03T02:00:00Z,13.7,226,3.2,6.8,67,1016.7,26.7,1,0.0,...,9999,0.0,0.0,0.0,0.0,0.0,0,-9,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,2026-08-11T00:00:00Z,14.0,235,3.1,6.8,88,1013.2,17.9,0,0.0,...,7050,5.6,1.4,1.5,4.8,0.0,42,0,1,3
79,2026-08-11T12:00:00Z,19.2,263,4.2,9.9,54,1014.7,20.6,0,0.0,...,5877,0.0,0.7,1.7,3.1,0.0,28,0,1,3
80,2026-08-12T00:00:00Z,13.8,250,2.7,6.0,85,1016.3,18.7,0,0.0,...,6822,0.0,0.4,0.9,2.0,0.0,28,0,1,2
81,2026-08-12T12:00:00Z,19.3,277,3.7,8.9,53,1016.8,24.0,0,0.0,...,5474,0.0,0.6,1.1,2.9,0.0,26,0,1,3
82,2026-08-13T00:00:00Z,13.8,260,2.7,5.9,87,1017.3,9.7,0,0.0,...,7343,0.0,1.1,1.1,3.8,0.0,37,0,1,3

In [6]:
df.head()

,time,air_temperature,wind_from_direction,wind_speed,wind_speed_of_gust,relative_humidity,air_pressure_at_mean_sea_level,visibility_in_air,thunderstorm_probability,probability_of_frozen_precipitation,...,cloud_top_altitude,precipitation_amount_mean_deterministic,precipitation_amount_mean,precipitation_amount_min,precipitation_amount_max,precipitation_amount_median,probability_of_precipitation,precipitation_frozen_part,predominant_precipitation_type_at_surface,symbol_code
0,2026-08-02T22:00:00Z,15.9,228,2.7,6.6,55,1016.0,34.7,1,0.0,...,9999,0.0,0.0,0.0,0.0,0.0,0,-9,0,1
1,2026-08-02T23:00:00Z,15.2,228,3.1,6.2,58,1016.3,32.7,1,0.0,...,9999,0.0,0.0,0.0,0.0,0.0,0,-9,0,1
2,2026-08-03T00:00:00Z,14.9,234,3.6,7.2,60,1016.5,31.3,1,0.0,...,9999,0.0,0.0,0.0,0.0,0.0,0,-9,0,1
3,2026-08-03T01:00:00Z,14.4,234,3.5,7.4,63,1016.6,29.2,1,0.0,...,9999,0.0,0.0,0.0,0.0,0.0,0,-9,0,1
4,2026-08-03T02:00:00Z,13.7,226,3.2,6.8,67,1016.7,26.7,1,0.0,...,9999,0.0,0.0,0.0,0.0,0.0,0,-9,0,1